name: Build and Test

on:
  push:
    branches:
      - master
      - main
      - ci
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-22.04]
        java: [17]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java ${{ matrix.java }}
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: "Set environmental variables"
        run: |
          echo "PH4_TEST=1" >> $GITHUB_ENV

      - name: Build
        run: |
          ./gradlew build
          ./gradlew test

